# Generated by Django 3.1.4 on 2020-12-20 12:21

from django.db import migrations, models
import django.db.models.deletion
import foodstuffs.utilities


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name_dimension', models.CharField(max_length=50, verbose_name='сокращенное название размерности')),
                ('full_name_dimension', models.CharField(max_length=100, verbose_name='полное название размерности')),
                ('description_dimension', models.TextField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Размерность',
                'verbose_name_plural': 'Размерности',
                'ordering': ['short_name_dimension'],
            },
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_recipe', models.CharField(max_length=70, verbose_name='Название рецепта')),
                ('description_recipe', models.TextField(max_length=300, verbose_name='Описание рецепта')),
                ('photo_of_recipe', models.ImageField(blank=True, upload_to=foodstuffs.utilities.get_timestamp_path, verbose_name='Избражение рецепта')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
                'ordering': ['name_recipe'],
            },
        ),
        migrations.CreateModel(
            name='TypeProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_type_product', models.CharField(max_length=50, verbose_name='тип продуктов')),
            ],
            options={
                'verbose_name': 'Тип продуктов',
                'verbose_name_plural': 'Типы продуктов',
                'ordering': ['name_type_product'],
            },
        ),
        migrations.CreateModel(
            name='TypeRecipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_type_recipes', models.CharField(max_length=70)),
                ('description_type_recipes', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='StepsOfCooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_step', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('step_cooking', models.TextField(max_length=300, verbose_name='Этап приготовения')),
                ('time_cooking', models.TimeField(blank=True, null=True, verbose_name='Время выполнения этапа')),
                ('photo_of_step', models.ImageField(blank=True, upload_to=foodstuffs.utilities.get_timestamp_path, verbose_name='Избражение')),
                ('recip_for_steps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodstuffs.recipes', verbose_name='рецепт')),
            ],
            options={
                'verbose_name': 'Этап приготовления',
                'verbose_name_plural': 'Этапы приготовления',
                'ordering': ['order_step'],
            },
        ),
        migrations.AddField(
            model_name='recipes',
            name='type_recipes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='foodstuffs.typerecipes', verbose_name='Тип рецепта'),
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=70, verbose_name='название продукта')),
                ('kcal_product', models.PositiveIntegerField(blank=True, null=True, verbose_name='Килокаллории')),
                ('type_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='foodstuffs.typeproducts', verbose_name='тип продукта')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['name_product'],
            },
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_ingredient', models.PositiveIntegerField(verbose_name='количество')),
                ('dimension_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='foodstuffs.dimension', verbose_name='размерность')),
                ('name_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='foodstuffs.products', verbose_name='название ингредиента')),
                ('recipe_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodstuffs.recipes', verbose_name='рецепт')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
                'ordering': ['name_ingredient'],
            },
        ),
        migrations.CreateModel(
            name='SubTypeRecipes',
            fields=[
            ],
            options={
                'verbose_name': 'Подтип рецептов',
                'verbose_name_plural': 'Подтипы рецептов',
                'ordering': ['super_type_recipe__name_type_recipes', 'name_type_recipes'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('foodstuffs.typerecipes',),
        ),
        migrations.CreateModel(
            name='SuperTypeRecipes',
            fields=[
            ],
            options={
                'verbose_name': 'Надтип рецептов',
                'verbose_name_plural': 'Надтипы рецептов',
                'ordering': ['name_type_recipes'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('foodstuffs.typerecipes',),
        ),
        migrations.AddField(
            model_name='typerecipes',
            name='super_type_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='foodstuffs.supertyperecipes', verbose_name='Надтип рецептов'),
        ),
    ]
